export const pinterest = [
  {
    rank: 1,
    name: "Fairy Tail",
    description: "Mashima Hiro",
    image: "https://i.imgur.com/cWy4bRs.jpeg",
    url: "https://i.imgur.com/cWy4bRs.jpeg",
  },
  {
    rank: 2,
    name: "Bleach",
    description: "Kubo Taito",
    image: "https://i.imgur.com/kYQP9ov.jpeg",
    url: "https://i.imgur.com/kYQP9ov.jpeg",
  },
  {
    rank: 3,
    name: "One Piece",
    description: "Oda Eiichiro",
    image: "https://i.imgur.com/mDDgpte.jpeg",
    url: "https://i.imgur.com/mDDgpte.jpeg",
  },
  {
    rank: 4,
    name: "Naruto",
    description: "Kishimoto Masashi",
    image: "https://i.imgur.com/JvhPBuG.jpeg",
    url: "https://i.imgur.com/JvhPBuG.jpeg",
  },
  {
    rank: 5,
    name: "Kyoutai No Katana",
    description: "Torii Nagomu",
    image: "https://i.imgur.com/Q8APZze.gif",
    url: "hhttps://i.imgur.com/Q8APZze.gif",
  },
  {
    rank: 6,
    name: "Attack on Titan",
    description: "Hajime Isayama",
    image: "https://i.imgur.com/OqsrNpH.jpeg",
    url: "https://i.imgur.com/OqsrNpH.jpeg",
  },
  {
    rank: 7,
    name: "Death Note",
    description: "Tsugumi Ohba, Takeshi Obata",
    image: "https://i.imgur.com/c4PGPkB.jpeg",
    url: "https://i.imgur.com/c4PGPkB.jpeg",
  },
  {
    rank: 8,
    name: "Kimetsu no Yaiba",
    description: "	Gotōge Koyoharu",
    image: "https://i.imgur.com/0pvabbZ.jpeg",
    url: "https://i.imgur.com/0pvabbZ.jpeg",
  },
  {
    rank: 9,
    name: "Sword Art Online",
    description: "Reki Kawahara",
    image: "https://i.imgur.com/OeSH3KT.gif",
    url: "https://i.imgur.com/OeSH3KT.gif",
  },
  {
    rank: 10,
    name: "Tokyo Ghoul",
    description: "Sui Ishida",
    image: "https://i.imgur.com/KjpqPCu.gif",
    url: "https://i.imgur.com/KjpqPCu.gif",
  },
  { rank: 11,
    name: "Hellsing",
    description: "Kouta Hirano",
    image: "https://i.imgur.com/jCyaM4c.gif",
    url: "https://i.imgur.com/jCyaM4c.gif",
  },
  {
    rank: 12,
    name: "Monster",
    description: "Urasawa Naoki",
    image: "https://i.imgur.com/76BGwkJ.gif",
    url: "https://i.imgur.com/76BGwkJ.gif",
  },
];
